### ISSUE TITLE
Players get kicked from boats and can't ride them again

### ISSUE THREAD

**Issue by MithrandirCraft** [Xevenut/BetterChair#1]
Players get kicked from boats, and possibly other rideable entities and can't ride them again for a while.

Boats: This is easily reproduceable, all you have to do is place a boat on water and go for a ride. After less than a minute you should be capable of experiencing the kick-out.

BetterChair v 1.7.0

**Comment by Xevenut** [comment]
Hi MithrandirCraft,

I got in a boat for just under 3 minutes and drove around and nothing happened. Can you upload a video to youtube and send me your error code?

**Comment by MithrandirCraft** [comment]
The thing is, I reproduced this issue in around 30s with BetterChair installed, then I uninstalled it, and moved around for at least 3 minutes and could no longer reproduce it.

Still it's a pretty common issue, but still, can't really 100% confirm it's BetterChair.

**Comment by Xevenut** [comment]
How should I then see that it is BetterChair? I cannot repeat it with this information.

**Comment by MithrandirCraft** [comment]
Yup, I guess you can't. I'll let you know if I find out anything else. Feel free to close the ticket, or leave it open, whatever. I'll close it myself if I can confirm this is irrelated to your plugin.
