### ISSUE TITLE
Players stand up when hit, in protected WorldGuard PvP flag "deny" area.

### ISSUE THREAD

**Issue by MithrandirCraft** [Xevenut/BetterChair#2]
The title is self explanatory, but the issue goes beyond WorldGuard really.

Players who aren't taking damage shouldn't be caused to stand up, for example, in worldguard areas protected against PvP, players shouldn't be forced to stand up if hit (no damage is applied, hence pvp cannot start).

This may internally be an event priority issue or similar.

**Comment by Xevenut** [comment]
You're right. but it's not a function that I offer. But I'll be happy to build it in for you. PVP and MOB-DAMAGE flag is enough?

**Comment by Xevenut** [comment]
Download Update: https://www.spigotmc.org/resources/betterchair.71734/download?version=452652

**Comment by MithrandirCraft** [comment]
This is now fixed, thanks.
