### ISSUE TITLE
Context: Protection Plugins, Breaking the block below a sitting player makes player stand up

### ISSUE THREAD

**Issue by MithrandirCraft** [Xevenut/BetterChair#3]
If sitting on a protected area against block breaking, if a player breaks the block beneath me, he causes me to stand up, even if the block break event gets presumably cancelled. The brief ticks where the block is actually broken seem to break the chair, causing me to stand up, even though the chair block will actually remain in place.

In my case this happens with WorldGuard and GriefDefender, but it could happen with any other region protecting plugin.

**Comment by Xevenut** [comment]
I can't recreate that. I have set the build flag to deny and the block is not dismantled. I used the BlockBreakEvent to detect it. WorldGuard and other plugins do not send or block a BlockBreakEvent when it is not allowed to happen.

What flag are you using in WorldGuard?

Are you sure that the breaking is really blocked and not just undone?

Can you make me a video of this, maybe I'm just misunderstanding you?

**Comment by MithrandirCraft** [comment]
> Are you sure that the breaking is really blocked and not just undone?

It is undone. I do not know if this means the event has been cancelled, or if this is the only programatical way of denying block breaking. My example is with WorldGuard and I know there's a few frames where the block disappears, it's how most protection plugins work.

The following video should answer your other questions: https://youtu.be/DcUBdVsyInU

**Comment by Xevenut** [comment]
In WorldGuard, the "build" flag is used to control the dismantling process. I see that you do not use this. Is it possible that another plugin prevents the build?
Can you send me your plugin list?

**Comment by Xevenut** [comment]
Can you send me your plugin list?

**Comment by MithrandirCraft** [comment]
Oh yeah, u'r right, there is another plugin on top of that, it's GriefDefender. Both the WG and GD areas are one on top of the other... However, GD has nothing to do with this, since it also happens in my hub, which doesn't have GD installed, or any other protection plugins which aren't WorldGuard.

Also, I installed WorldGuard on a clean server the other day, and it seems to protect region included blocks by default... this is probably because the build flag is "deny" by default, even if unlisted.

It's just how WG works.

**Comment by Xevenut** [comment]
[BetterChair.zip](https://github.com/Xevenut/BetterChair/files/8809871/BetterChair.zip)
I guess it's one of your other area protection plugins. I made a version for you that tries to use the BlockBreakEvent last and works after your plugins if necessary. If that doesn't work I think the problem is with one of your area protection plugins. If the BlockBreakEvent is triggered and the block is only set again afterwards, the other programmer of your area protection plugin has included a logic error. Let me know if it worked :D

**Comment by MithrandirCraft** [comment]
> BlockBreakEvent is triggered
All mentions of blockbreakevent by my side where pure speculation. I don't really know what's going on internally with WorldGuard. The only thing I can clearly see is that WG (and other protection plugins I don't necesarily use) protect blocks by rolling them back. There is however, a few frames in which the block disappears, I believe, when broken, even when it gets quickly automatically placed again.

I installed your version on my hub server, the plugins there are the following:

AuthMe, BetterChair, BungeeTabListPlus, ChatControlRed, Citizens, CustomJukebox, EnjinMinecraftPlugin, Essentials, EssentialsSpawn, FastAsyncWorldEdit (WorldEdit), FastLogin, HolographicDisplays, JukeboxRegion*, LuckPerms, MiniaturePets, MythicMobs, PlaceholderAPI, PlayerHeads, PremiumVanish, ProtocolLib, ServerSelectorX, SimpleHubParkour, SkinsRestorer, Spartan, Vault, VoidSpawn, WorldGuard

**However the symptoms are exactly the same**. The only applied protection where I was sitting is worldguard area with the build flag defaulting deny.

> the other programmer of your area protection plugin has included a logic error

I doubt this is WorldGuard's fault, I'd say it's just what happens with minecraft servers when the blockbreak event is tampered with. I haven't seen a single minecraft server where this block dissappearing phenomenon with blocks reappearing after a few frames, with protection plugins, wasn't present. (Unless they set you into adventure mode, where you just can't break).

**Comment by Xevenut** [comment]
I think you misunderstand me. I don't mean that WorldGuard has the problem. WorldGuard runs as it should. Another plugin is doing the blocking for you, not WorldGuard. WorldGuard would stop it correctly, with you by another plugin the block is reset, with WorldGuard is directly blocked the dismantling.

Please check which plugin blocks the removal of a block at this point.

I repeat WorldGuard does not block the removal of blocks with your current settings, another plugin takes over this task for you. Please name this plugin.

**Comment by MithrandirCraft** [comment]
> Please check which plugin blocks the removal of a block at this point.
No other plugin is blocking world block placement/removal on my hub server (and it wouldn't make sense for them to).

But just to make sure, I reproduced this with the following steps:

1. Create a clean Paper 1.18.2 server.
2. Install BetterChair, WorldEdit & WorldGuard plugins.
3. Define a region with WorldGuard.
4. Log into the server with 2 players.
5. While inside the WorldGuard area, sit down with one player.
6. Use the other player to break the block beneath the sitting account.

100% reproduction consistency. The whole process will look exactly like what I showed you in the video, just that I confirmed this on a clean server with just BC, WE & WG plugins installed.

Please try this yourself in order to notice the problem.

A posible solution would be to preserve the chair ("sitting player lock") for a few ticks after it has been destroyed (this could also be used as a cooldown for chairs). You could even make it optional.

**Comment by Xevenut** [comment]
Is the "build" flag set to "deny"?

**Comment by MithrandirCraft** [comment]
> Is the "build" flag set to "deny"?

The "build" flag is not set at all in my example (all I did was create a region). I believe it is set to "deny" by default if unlisted.
I also made sure not to be OP'd with any of my players.

**Comment by Xevenut** [comment]
Please set this to "deny".

**Comment by MithrandirCraft** [comment]
I just added the build flag by setting it to deny on the same test region I mention in my reproduction steps.

The result is the same, the player sitting down stands up when you break the block beneath it, even though protected. I'm quite sure this was unnecesary `I believe it is set to "deny" by default if unlisted.`

**Comment by MithrandirCraft** [comment]
Have you tested this yourself?

**Comment by Xevenut** [comment]
This does not happen for me. Which version of WorldGuard are you using?

**Comment by Xevenut** [comment]
Send me your paper version as well. I always test this with the current Spigot version.

**Comment by MithrandirCraft** [comment]
![imagen](https://user-images.githubusercontent.com/6623704/171497476-d9b5d925-931a-4af0-aeea-50f860715f45.png)

Paper: git-Paper-333 (MC: 1.18.2)
WG: 7.0.7+216b061

BetterChair version is 1.9.0

**Comment by Xevenut** [comment]
[BetterChair.zip](https://github.com/Xevenut/BetterChair/files/8818731/BetterChair.zip)
Should be fixed now.
If that works, may I put your error video from Youtube with the update message on Spigot?

**Comment by MithrandirCraft** [comment]
It's fixed!

And yeah, go ahead and use that video for whatever you like.
